name: build-documentation
on: [push]
jobs:
  cmake-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Create build directory
      run: pwd && mkdir ${{github.workspace}}/build

    - name: Check current directory
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: pwd

    # - name: Invoke CMake
    #   run: cmake .. -DBUILD_DOC=ON -DQUIET_DOXYGEN=NO
    #
    # - name: Build documentation using Doxygen
    #   run: cmake --build . --target doc

  cmake-build-change-defaults:
    defaults:
      run:
        shell: bash
        working-directory: ${{github.workspace}}/build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Create build directory
      working-directory: ${{github.workspace}}
      run: pwd && mkdir ${{github.workspace}}/build

    - name: Check current directory
      run: pwd
