name: build-documentation
on: [push]
jobs:
  cmake-build:
    # Target OS: Ubuntu.
    runs-on: ubuntu-latest
    # Use bash for all commands.
    defaults:
      run:
        shell: bash

    steps:
    # Install CMake and Doxygen.
    - name: Install dependencies
      working-directory: ${{github.workspace}}
      run: sudo apt install cmake doxygen
    # Clone the repository.
    - uses: actions/checkout@v2
    # Create the build space.
    - name: Create build directory
      working-directory: ${{github.workspace}}
      run: mkdir ${{github.workspace}}/build
    # Configure CMake.
    - name: Invoke CMake
      working-directory: ${{github.workspace}}/build
      run: cmake .. -DBUILD_DOC=ON -DQUIET_DOXYGEN=NO
    # Run Doxygen to create the documentation.
    - name: Build documentation using Doxygen
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --target doc
    # Deploy the documentation to GitHub Pages.
    - name: Deploy documentation.
      run: echo "[DEPLOY DOC!]"
