name: build-documentation
on: [push]
jobs:
  cmake-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Create build directory
      run: pwd && mkdir ${{github.workspace}}/build && cd ${{github.workspace}}/build && pwd

    - name: Check current directory
      run: pwd

    # - name: Invoke CMake
    #   run: cmake .. -DBUILD_DOC=ON -DQUIET_DOXYGEN=NO
    #
    # - name: Build documentation using Doxygen
    #   run: cmake --build . --target doc
