name: build-documentation
on: [push]
jobs:
  cmake-build:
    # target OS
    runs-on: ubuntu-latest
    # make sure we are in the build folder by default
    defaults:
      run:
        shell: bash
        working-directory: ${{github.workspace}}/build

    steps:
    - uses: actions/checkout@v2

    - name: Check repo
      working-directory: ${{github.workspace}}
      run: ls

    - name: Create build directory
      run: pwd && mkdir ${{github.workspace}}/build

    - name: Check current directory
      run: pwd

    # - name: Invoke CMake
    #   run: cmake .. -DBUILD_DOC=ON -DQUIET_DOXYGEN=NO
    #
    # - name: Build documentation using Doxygen
    #   run: cmake --build . --target doc
